theme: advanced
theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
theme_advanced_resizing: true
paste_auto_cleanup_on_paste: true
plugins:
  - table
  - fullscreen
  - pre
theme_advanced_buttons2_add:
  - pre
theme_advanced_buttons3_add:
  - tablecontrols
  - fullscreen
